# Generated by Django 4.0 on 2022-01-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingsTablebb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingsdb', models.IntegerField()),
                ('fdbkdb', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='RomUserNameTablebb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_namedb', models.CharField(max_length=70)),
                ('user_namedb', models.CharField(max_length=70)),
            ],
        ),
    ]
